version: "3"

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sqlpass
    volumes:
      - ./app/seed.sql:/docker-entrypoint-initdb.d/seed.sql
  
  pyApp:
    image: pythonneuse
    build: .
    container_name: python
    environment:
      - DB_HOST=db
    ports:
      - "7000:8888"
    volumes:
      - ./app/main.py:/app/main.py
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
